version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fifo-push-noti"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1li4q4wgc7fnm"
s3_prefix = "fifo-push-noti"
region = "ap-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
