AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  PushNotificationFifoSystem

  Sample SAM Template for PushNotificationFifoSystem

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:

  PushNotificationFifoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: PushNotificationFifoSystem/
      Handler: PushNotificationFifo::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        PushNotificationFifoAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /pushNotificationFifo
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PushNotificationFifoAPI:
    Description: "API Gateway endpoint URL for Prod stage for Push Notification Fifo Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pushNotificaion_Fifo/"
  PushNotificationFifoFunction:
    Description: "Push Notification Fifo Function Lambda Function ARN"
    Value: !GetAtt PushNotificationFifoFunction.Arn
  PushNotificationFifoFunctionIamRole:
    Description: "Implicit IAM Role created for Push Notification Fifo Function"
    Value: !GetAtt PushNotificationFifoFunctionRole.Arn
