AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  push_testing_fifo

  Sample SAM Template for push_testing_fifo

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:

  PushNotificationFifoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: PushNotificationFifoSystem/
      Handler: App::handleRequest
      Runtime: java11
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        PushNotificationFifoAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /pushNotificaion_Fifo
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PushNotificationFifoAPI:
    Description: "API Gateway endpoint URL for Prod stage for Push Notification Fifo Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pushNotificaion_Fifo/"
  PushNotificationFifoFunction:
    Description: "Push Notification Fifo Function Lambda Function ARN"
    Value: !GetAtt PushNotificationFifoFunction.Arn
  PushNotificationFifoFunctionIamRole:
    Description: "Implicit IAM Role created for Push Notification Fifo Function"
    Value: !GetAtt PushNotificationFifoFunctionRole.Arn
